language: php
php:
  - 8.1
  - 8.0
  - 7.4
  - 5.6
before_script:
  - phpenv config-add .travis.php.ini
  - composer install
  - composer require predis/predis
script: phpunit --testdox --exclude-group=php-memcache
services:
  - memcached
  - redis-server
