 name: CI

 on: [push]

 jobs:
   build-test:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2
     - uses: php-actions/composer@v5
     - uses: php-actions/phpunit@v3
       with:
         configuration: ./phpunit.xml
         php_version: 7.4
         version: 9.4
         
           
