name: Unit tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: niden/actions-memcached@v7
      - uses: supercharge/redis-github-action@1.4.0
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php-version: 8.1
      - name: phpunit (php 8.2)
        uses: php-actions/phpunit@v3
        with:
          configuration: ./phpunit.xml
          php_extensions: memcache memcached
          php_version: 8.2
      - name: phpunit (php 8.3)
        uses: php-actions/phpunit@v3
        with:
          configuration: ./phpunit.xml
          php_extensions: memcache memcached
          php_version: 8.3
      - name: phpunit (php latest)
        uses: php-actions/phpunit@v3
        with:
          configuration: ./phpunit.xml
          php_extensions: memcache memcached
          php_version: latest
