 name: CI

 on: [push]

 jobs:
   #   test-latest:
   #  name: "Test latest"

   test-74:
     name: "Test 7.4"
     runs-on: ubuntu-latest
     steps:
     - uses: niden/actions-memcached@v7
     - uses: supercharge/redis-github-action@1.4.0
     - uses: actions/checkout@v2
     - uses: php-actions/composer@v5
     - uses: php-actions/phpunit@v3
       with:
         configuration: ./phpunit.xml
         php_extensions: memcache memcached
         php_version: 7.4
      - uses: php-actions/phpunit@v3
       with:
         configuration: ./phpunit.xml
         php_extensions: memcache memcached
         
           
