 name: CI

 on: [push]

 jobs:
   test74:
     name: "Test 7.4"
     runs-on: ubuntu-latest
     steps:
     - uses: niden/actions-memcached@v7
     - uses: supercharge/redis-github-action@1.4.0
     - uses: actions/checkout@v2
     - uses: php-actions/composer@v5
     - uses: php-actions/phpunit@v3
       with:
         configuration: ./phpunit.xml
         php_extensions: memcache memcached 
     - uses: php-actions/phpunit@v3
       with:
         configuration: ./phpunit.xml
         php_extensions: memcache memcached
         php_version: 8.0
         version: 9.5.18
     - uses: php-actions/phpunit@v3
       with:
         configuration: ./phpunit.xml
         php_extensions: memcache memcached
         php_version: 7.4
         version: 9.5.18
     - uses: php-actions/phpunit@v3
       with:
         configuration: ./phpunit.xml
         php_extensions: memcache memcached
         php_version: 5.6
         version: 5.7.27

